# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gartenblog
author: Sebastian Blei
author_link: https://sebastian.science
author_description: Blog um den eigenen Garten
email: me@sebastianblei.com
description: > # this means to ignore newlines until "baseurl:"
  Blog rund um den Garten von Sebastian Blei. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bot.sebastian.science" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id:

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty

# Pagination
paginate: 3

# Sass
sass:
    style: :compressed

# Directories
exclude:
  - create-jekyll-post-rs
  - new_post.sh
  - post_image.template
  - import_images
