# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
email: m@sebastian.science
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: 

# SEO settings
title: >
  Sebastian Blei: Brauen, Garten, Hacken & der Rest
description: > # this means to ignore newlines until "baseurl:"
  Sebastian Blei hält Notiz darüber, was er für Bier braut, im Garten baut und Bytecode kaut.
url: "http://sebastian.science" # the base hostname & protocol for your site
twitter_username: iamblei
default_img: http://orig06.deviantart.net/11ba/f/2012/272/4/7/redfuck_by_redfuck-d5g91if.jpg
author: Sebastian Blei
author_link: http://sebastian.science
#author_description: >
  #Brauen, Garten, Hacken von und mit Sebastian Blei & Söhnen
author_description: >
  Brauen, Garten, Hacken

# Profile settings
name: Sebastian Blei
profile_img: http://orig06.deviantart.net/11ba/f/2012/272/4/7/redfuck_by_redfuck-d5g91if.jpg
profile: >
  Brauherr, Gärtner, Hacker und Pflanzenfreund Sebastian Blei.
social:
  github: https://github.com/iamsebastian

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
# From galileo-theme
#picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
# From galileo-theme
#typekit_kit_id:

# Build settings
include: ["_categories"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 999
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed

# Gems
plugins: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

# Flickr
flickr:
  screen_name: wolkenphysiker
  api_key: 78b917cd42fafef19785713616f06143
  api_secret: 64ee7d969d880f19

  generate_posts: true
  generate_photosets:
    - "sebastian.science"
  generate_frontmatter:
    layout: flickr_photo
    author: wolkenphysiker
  use_cache: true
  cache_dir: _flickr

  size_full: Original
  size_thumb: "Large Square"

# Directories
exclude:
  - vendor
  - create-jekyll-post-rs
  - new_post.sh
  - post_image.template
  - import_images
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - categories.sh
