# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
email: m@sebastian.science
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics:

# SEO settings
title: >
  Sebastian Blei: Brauen, Garten, Hacken & der Rest
description: > # this means to ignore newlines until "baseurl:"
  Sebastian Blei hält Notiz darüber, was er für Bier braut, im Garten baut und Bytecode kaut.
url: "http://sebastian.science" # the base hostname & protocol for your site
twitter_username: iamblei
default_img: http://orig06.deviantart.net/11ba/f/2012/272/4/7/redfuck_by_redfuck-d5g91if.jpg
author: Sebastian Blei
author_link: http://sebastian.science
#author_description: >
  #Brauen, Garten, Hacken von und mit Sebastian Blei & Söhnen
author_description: >
  Brauen, Garten, Hacken

# Profile settings
name: Sebastian Blei
profile_img: http://orig06.deviantart.net/11ba/f/2012/272/4/7/redfuck_by_redfuck-d5g91if.jpg
profile: >
  Brauherr, Gärtner, Hacker und Pflanzenfreund Sebastian Blei.
social:
  github: https://github.com/iamsebastian

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
# From galileo-theme
#picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
# From galileo-theme
#typekit_kit_id:

# Build settings
include: ["_categories"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Pagination
#paginate: 999
#paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed

# Gems
plugins: [jekyll-paginate-v2, jekyll-sitemap, octopress-autoprefixer]

# Flickr
flickr:
  screen_name: wolkenphysiker
  api_key: 78b917cd42fafef19785713616f06143
  api_secret: 64ee7d969d880f19

  generate_posts: true
  generate_photosets:
    - "sebastian.science"
  generate_frontmatter:
    layout: flickr_photo
    author: wolkenphysiker
  use_cache: false
  cache_dir: _flickr

  size_full: Original
  size_thumb: "Large Square"

# Directories
exclude:
  - vendor
  - create-jekyll-post-rs
  - new_post.sh
  - post_image.template
  - import_images
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - categories.sh


############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/blog/page-:num/' # Pages are index.html inside this folder (default)
  #permalink: '/blog/page-:num.html' # Pages are simple html files
  #permalink: '/blog/page-:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################
